"""empty message

Revision ID: 089bd941b887
Revises: 
Create Date: 2022-04-22 12:01:33.883851

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '089bd941b887'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('timestamp', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_comment_timestamp'), 'comment', ['timestamp'], unique=False)
    op.add_column('topic', sa.Column('timestamp', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_topic_timestamp'), 'topic', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_topic_timestamp'), table_name='topic')
    op.drop_column('topic', 'timestamp')
    op.drop_index(op.f('ix_comment_timestamp'), table_name='comment')
    op.drop_column('comment', 'timestamp')
    # ### end Alembic commands ###
