"""add trainings table

Revision ID: 151c5a301993
Revises: ac1c039b8793
Create Date: 2022-04-24 21:29:18.882743

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '151c5a301993'
down_revision = 'ac1c039b8793'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('training',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['group.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('training')
    # ### end Alembic commands ###
