"""training user

Revision ID: 35006d3e64dd
Revises: 151c5a301993
Create Date: 2022-04-24 21:47:44.391979

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35006d3e64dd'
down_revision = '151c5a301993'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('training', sa.Column('couch_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'training', 'user', ['couch_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'training', type_='foreignkey')
    op.drop_column('training', 'couch_id')
    # ### end Alembic commands ###
