"""type name

Revision ID: 47428e7ee7c8
Revises: f61128cde946
Create Date: 2022-04-23 00:55:42.377963

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47428e7ee7c8'
down_revision = 'f61128cde946'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('type', sa.Column('name', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('type', 'name')
    # ### end Alembic commands ###
