"""card img

Revision ID: 4b31a36f77e2
Revises: e1416bddf18e
Create Date: 2022-04-19 23:14:18.311391

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b31a36f77e2'
down_revision = 'e1416bddf18e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('card', sa.Column('image', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('card', 'image')
    # ### end Alembic commands ###
