"""afv

Revision ID: 7f4348715732
Revises: 
Create Date: 2022-05-27 19:51:13.987231

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f4348715732'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('password', sa.String(length=100), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('collection',
    sa.Column('card_id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.String(length=8), nullable=True),
    sa.Column('label', sa.String(length=40), nullable=True),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('sec_name', sa.String(length=50), nullable=True),
    sa.Column('contact_number', sa.String(length=20), nullable=True),
    sa.Column('mail', sa.String(length=30), nullable=True),
    sa.Column('adress', sa.String(length=30), nullable=True),
    sa.Column('birthday', sa.String(length=10), nullable=True),
    sa.Column('social_media', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('card_id')
    )
    op.create_index(op.f('ix_collection_timestamp'), 'collection', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_collection_timestamp'), table_name='collection')
    op.drop_table('collection')
    op.drop_table('user')
    # ### end Alembic commands ###
