"""gr

Revision ID: dcb9fa70c927
Revises: 876f35ad9c7b
Create Date: 2022-04-26 14:43:23.314112

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dcb9fa70c927'
down_revision = '876f35ad9c7b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('group_',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('group')
    op.drop_constraint(None, 'student', type_='foreignkey')
    op.create_foreign_key(None, 'student', 'group_', ['group_id'], ['id'])
    op.drop_constraint(None, 'training', type_='foreignkey')
    op.create_foreign_key(None, 'training', 'group_', ['group_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'training', type_='foreignkey')
    op.create_foreign_key(None, 'training', 'group', ['group_id'], ['id'])
    op.drop_constraint(None, 'student', type_='foreignkey')
    op.create_foreign_key(None, 'student', 'group', ['group_id'], ['id'])
    op.create_table('group',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('text', sa.VARCHAR(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('group_')
    # ### end Alembic commands ###
