"""cards fields v1

Revision ID: e1416bddf18e
Revises: 9663868c2d51
Create Date: 2022-04-19 21:52:42.603178

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1416bddf18e'
down_revision = '9663868c2d51'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('card', sa.Column('firstName', sa.String(length=100), nullable=True))
    op.add_column('card', sa.Column('middleName', sa.String(length=100), nullable=True))
    op.add_column('card', sa.Column('lastName', sa.String(length=100), nullable=True))
    op.add_column('card', sa.Column('birthDate', sa.Date(), nullable=True))
    op.add_column('card', sa.Column('favColor', sa.String(length=100), nullable=True))
    op.add_column('card', sa.Column('favFood', sa.String(length=100), nullable=True))
    op.add_column('card', sa.Column('personalityType', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('card', 'personalityType')
    op.drop_column('card', 'favFood')
    op.drop_column('card', 'favColor')
    op.drop_column('card', 'birthDate')
    op.drop_column('card', 'lastName')
    op.drop_column('card', 'middleName')
    op.drop_column('card', 'firstName')
    # ### end Alembic commands ###
